### ISSUE TITLE
如何卸载呢？

### ISSUE THREAD

**Issue by liuxueyang** [slackwarecn-slackbuilds/WineQQ-Assistant#2]
删除掉`$HOME/.wine`目录就可以了吗？还需要做别的事情吗？

**Comment by nnnewb** [comment]
以下几个目录
安装时`WINEQQ_PREFIX`指定的目录，默认是$HOME/.wine
如果没有安装wine，会自动下载playonlinux，wine保存在$HOME/.winevers
图标，保存在$HOME/.local/share/icons/hicolor/256x256/apps，应该是叫WineQQ.png
如果没有安装过，会自动下载安装文泉驿字体，保存在$HOME/.fonts/wqy-microhei.ttc
在/usr/share/wine/font.disable可能有一些tahoma字体，你可以选择把它们放回/usr/share/wine/fonts。如果系统没有装wine是脚本给你装的，那就不用管。
desktop文件，$HOME/.local/share/applications/wineqq.desktop
如果你想彻底删除无残留的话把这些处理掉就行了
wine自己也会产生一些没用的文件，酌情处理吧。

**Comment by nnnewb** [comment]
不过讲道理的说，卸载时只有这几个是需要处理的
$HOME/.wine
$HOME/.winevers
其他零零碎碎的没什么影响
$HOME/.local/share/applications/wineqq.desktop
这个你要一直能在菜单里（不是收藏）看到QQ的图标的话就删掉。

**Comment by liuxueyang** [comment]
@nnnewb  谢谢！已解决。
